### PR TITLE
add deploy tokens

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a824719 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a824719 with merge a824719...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/rustfmt-bin/build/1.0.1)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2793947 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2793947 with merge 2793947...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustfmt-bin/build/1.0.2), [status-travis](https://travis-ci.org/japaric/rustfmt-bin/builds/175609677)
Approved by: japaric
Pushing 279394702a988c1320a585a1584cd6667e9b7aee to master...

**Pull request merged**
